[workspace]
    members = [
        "./syscall-api/api-v0/",
        "./syscall-impl/impl-kernel/",
    ]

[package]
    name = "wateros-syscall"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    abi = { path = "../wateros-abi/", package = "wateros-abi", default-features = false, optional = true }
    api-v0 = { path = "./syscall-api/api-v0/", package = "wateros-syscall-api-v0", default-features = true, optional = true }
    impl-kernel = { path = "./syscall-impl/impl-kernel/", package = "wateros-syscall-impl-kernel", default-features = false, optional = true }

[features]
    api-v0 = [ "dep:abi", "abi/api-v0", "dep:api-v0", "impl-kernel?/api-v0" ]
    default = []
    impl-kernel = [ "api-v0", "dep:impl-kernel", "impl-kernel/fd-session" ]
    impl-loongarch64 = [
        "api-v0",
        "impl-kernel",
        "impl-kernel/impl-loongarch64",
    ]
    impl-riscv64 = [
        "api-v0",
        "impl-kernel",
        "impl-kernel/impl-riscv64",
    ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
