[workspace]

[package]
    name = "wateros-syscall"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    abi = { path = "../wateros-abi/", package = "wateros-abi", default-features = true, features = [
        "impl-linux-riscv64",
    ] }
    task = { path = "../wateros-task/", package = "wateros-task", default-features = true }
    console = { path = "../wateros-runtime/runtime-console/", package = "wateros-runtime-console", default-features = true }

[features]
    default = []
    impl-loongarch64 = [ "task/impl-loongarch64" ]
    impl-riscv64 = [ "task/impl-riscv64" ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
