[workspace]

[package]
    name = "wateros-syscall"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    abi = { path = "../wateros-abi/", package = "wateros-abi", default-features = false }
    task = { path = "../wateros-task/", package = "wateros-task", default-features = false }
    ipc = { path = "../wateros-ipc/", package = "wateros-ipc", default-features = false, optional = true }
    base = { path = "../wateros-base/", package = "wateros-base", default-features = true }
    console = { path = "../wateros-runtime/runtime-console/", package = "wateros-runtime-console", default-features = false }
    mm = { path = "../wateros-mm/", package = "wateros-mm", default-features = false, optional = true, features = [
        "api-v0",
        "impl-sv39",
    ] }

[features]
    default = []
    impl-loongarch64 = [
        "abi/api-v0",
        "abi/impl-linux-loongarch64",
        "console/impl-firmware-console",
        "dep:ipc",
        "ipc/impl-loongarch64",
        "ipc/pipe",
        "task/api-v0",
        "task/impl-core",
        "task/impl-loongarch64",
        "task/impl-round-robin",
    ]
    impl-riscv64 = [
        "abi/api-v0",
        "abi/impl-linux-riscv64",
        "console/impl-firmware-opensbi",
        "dep:ipc",
        "ipc/impl-riscv64",
        "ipc/pipe",
        "dep:mm",
        "task/api-v0",
        "task/impl-core",
        "task/impl-riscv64",
        "task/impl-round-robin",
    ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
