[package]
    name = "wateros-platform-arch-api-v0"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    base = { path = "../../../../wateros-base/", package = "wateros-base", default-features = true }
    syscall-api = { path = "../../../../wateros-syscall/syscall-api/api-v0/", package = "wateros-syscall-api-v0", default-features = true }
