[package]
    name = "wateros-platform-arch-api-v0"
    version = "0.1.0"
    edition = "2024"

[dependencies]
base = { path = "../../../../wateros-base/", package = "wateros-base", default-features = true }
    abi = { path = "../../../../wateros-abi/", package = "wateros-abi", features = [
        "api-v0",
    ] }
