// Syscall 号单次 match 分发（H-3）：替代 `SyscallKind::decode` + 巨型 match。
// 本模块代码由AI完成

use crate::sys;
use api_v0::SyscallArgs;

/// 按裸 syscall 号分发；未命中时走旁路号与 ENOSYS。
#[inline]
// 本方法代码由AI完成
pub fn dispatch_syscall_by_nr(syscall_nr : usize, syscall_args : SyscallArgs) -> isize {
    match syscall_nr {
        n if n == api_v0::YIELD => sys::sys_yield().0,
        n if n == api_v0::SCHED_SETPARAM => sys::sys_sched_setparam(syscall_args).0,
        n if n == api_v0::SCHED_SETSCHEDULER => sys::sys_sched_setscheduler(syscall_args).0,
        n if n == api_v0::SCHED_GETSCHEDULER => sys::sys_sched_getscheduler(syscall_args).0,
        n if n == api_v0::SCHED_GETPARAM => sys::sys_sched_getparam(syscall_args).0,
        n if n == api_v0::SCHED_SETAFFINITY => sys::sys_sched_setaffinity(syscall_args).0,
        n if n == api_v0::SCHED_GETAFFINITY => sys::sys_sched_getaffinity(syscall_args).0,
        n if n == api_v0::SCHED_GET_PRIORITY_MAX => sys::sys_sched_get_priority_max(syscall_args).0,
        n if n == api_v0::SCHED_GET_PRIORITY_MIN => sys::sys_sched_get_priority_min(syscall_args).0,
        n if n == api_v0::GETCPU => sys::sys_getcpu(syscall_args).0,
        n if n == api_v0::EXIT => sys::sys_exit(syscall_args.arg(0) as isize),
        n if n == api_v0::EXIT_GROUP => sys::sys_exit_group(syscall_args.arg(0) as isize),
        n if n == api_v0::READ => sys::sys_read(syscall_args).0,
        n if n == api_v0::READV => sys::sys_readv(syscall_args).0,
        n if n == api_v0::WRITE => sys::sys_write(syscall_args).0,
        n if n == api_v0::WRITEV => sys::sys_writev(syscall_args).0,
        n if n == api_v0::PREAD64 => sys::sys_pread64(syscall_args).0,
        n if n == api_v0::PWRITE64 => sys::sys_pwrite64(syscall_args).0,
        n if n == api_v0::PREADV => sys::sys_preadv(syscall_args).0,
        n if n == api_v0::PWRITEV => sys::sys_pwritev(syscall_args).0,
        n if n == api_v0::SENDFILE => sys::sys_sendfile(syscall_args).0,
        n if n == api_v0::FADVISE64 => sys::sys_fadvise64(syscall_args).0,
        n if n == api_v0::READLINKAT => sys::sys_readlinkat(syscall_args).0,
        n if n == api_v0::FACCESSAT => sys::sys_faccessat(syscall_args).0,
        n if n == api_v0::FCHDIR => sys::sys_fchdir(syscall_args).0,
        n if n == api_v0::FCHMOD => sys::sys_fchmod(syscall_args).0,
        n if n == api_v0::FCHMODAT => sys::sys_fchmodat(syscall_args).0,
        n if n == api_v0::FCHOWN => sys::sys_fchown(syscall_args).0,
        n if n == api_v0::FCHOWNAT => sys::sys_fchownat(syscall_args).0,
        n if n == api_v0::STATFS => sys::sys_statfs(syscall_args).0,
        n if n == api_v0::SYNC => sys::sys_sync(syscall_args).0,
        n if n == api_v0::FSYNC => sys::sys_fsync(syscall_args).0,
        n if n == api_v0::FDATASYNC => sys::sys_fdatasync(syscall_args).0,
        n if n == api_v0::TRUNCATE => sys::sys_truncate(syscall_args).0,
        n if n == api_v0::FTRUNCATE => sys::sys_ftruncate(syscall_args).0,
        n if n == api_v0::FALLOCATE => sys::sys_fallocate(syscall_args).0,
        n if n == api_v0::OPENAT => sys::sys_openat(syscall_args).0,
        n if n == api_v0::CLOSE => sys::sys_close(syscall_args).0,
        n if n == api_v0::FSTAT => sys::sys_fstat(syscall_args).0,
        n if n == api_v0::LSEEK => sys::sys_lseek(syscall_args).0,
        n if n == api_v0::DUP => sys::sys_dup(syscall_args).0,
        n if n == api_v0::DUP3 => sys::sys_dup3(syscall_args).0,
        n if n == api_v0::PIPE2 => sys::sys_pipe2(syscall_args).0,
        n if n == api_v0::EVENTFD2 => sys::sys_eventfd2(syscall_args).0,
        n if n == api_v0::IOCTL => sys::sys_ioctl(syscall_args).0,
        n if n == api_v0::FCNTL => sys::sys_fcntl(syscall_args).0,
        n if n == api_v0::FLOCK => sys::sys_flock(syscall_args).0,
        n if n == api_v0::GETDENTS64 => sys::sys_getdents64(syscall_args).0,
        n if n == api_v0::MKDIRAT => sys::sys_mkdirat(syscall_args).0,
        n if n == api_v0::SYMLINKAT => sys::sys_symlinkat(syscall_args).0,
        n if n == api_v0::UNLINKAT => sys::sys_unlinkat(syscall_args).0,
        n if n == api_v0::RENAMEAT => sys::sys_renameat(syscall_args).0,
        n if n == api_v0::RENAMEAT2 => sys::sys_renameat2(syscall_args).0,
        n if n == api_v0::UTIMENSAT => sys::sys_utimensat(syscall_args).0,
        n if n == api_v0::MOUNT => sys::sys_mount(syscall_args).0,
        n if n == api_v0::UMOUNT2 => sys::sys_umount2(syscall_args).0,
        n if n == api_v0::BRK => sys::sys_brk(syscall_args.arg(0)).0,
        n if n == api_v0::FORK => sys::sys_clone(syscall_args).0,
        n if n == api_v0::CLONE3 => sys::sys_clone3(syscall_args).0,
        n if n == api_v0::UNSHARE => sys::sys_unshare(syscall_args).0,
        n if n == api_v0::EXEC => sys::sys_execve(syscall_args).0,
        n if n == api_v0::MMAP => sys::sys_mmap(syscall_args).0,
        n if n == api_v0::MUNMAP => sys::sys_munmap(syscall_args).0,
        n if n == api_v0::MSYNC => sys::sys_msync(syscall_args).0,
        n if n == api_v0::MPROTECT => sys::sys_mprotect(syscall_args).0,
        n if n == api_v0::MREMAP => sys::sys_mremap(syscall_args).0,
        n if n == api_v0::MADVISE => sys::sys_madvise(syscall_args).0,
        n if n == api_v0::MLOCK => sys::sys_mlock(syscall_args).0,
        n if n == api_v0::MUNLOCK => sys::sys_munlock(syscall_args).0,
        n if n == api_v0::MLOCKALL => sys::sys_mlockall(syscall_args).0,
        n if n == api_v0::MUNLOCKALL => sys::sys_munlockall(syscall_args).0,
        n if n == api_v0::GET_MEMPOLICY => sys::sys_get_mempolicy(syscall_args).0,
        n if n == api_v0::SHMGET => sys::sys_shmget(syscall_args).0,
        n if n == api_v0::SHMCTL => sys::sys_shmctl(syscall_args).0,
        n if n == api_v0::SHMAT => sys::sys_shmat(syscall_args).0,
        n if n == api_v0::SHMDT => sys::sys_shmdt(syscall_args).0,
        n if n == api_v0::GET_TIME => sys::sys_gettimeofday(syscall_args).0,
        n if n == api_v0::CLOCK_SETTIME => sys::sys_clock_settime(syscall_args).0,
        n if n == api_v0::CLOCK_GETTIME => sys::sys_clock_gettime(syscall_args).0,
        n if n == api_v0::CLOCK_GETRES => sys::sys_clock_getres(syscall_args).0,
        n if n == api_v0::CLOCK_NANOSLEEP => sys::sys_clock_nanosleep(syscall_args).0,
        n if n == api_v0::TIMER_CREATE => sys::sys_timer_create(syscall_args).0,
        n if n == api_v0::TIMER_GETTIME => sys::sys_timer_gettime(syscall_args).0,
        n if n == api_v0::TIMER_GETOVERRUN => sys::sys_timer_getoverrun(syscall_args).0,
        n if n == api_v0::TIMER_SETTIME => sys::sys_timer_settime(syscall_args).0,
        n if n == api_v0::TIMER_DELETE => sys::sys_timer_delete(syscall_args).0,
        n if n == api_v0::GETPID => sys::sys_getpid().0,
        n if n == api_v0::GETPPID => sys::sys_getppid().0,
        n if n == api_v0::GETTID => sys::sys_gettid().0,
        n if n == api_v0::GETUID => sys::sys_getuid().0,
        n if n == api_v0::GETEUID => sys::sys_geteuid().0,
        n if n == api_v0::GETGID => sys::sys_getgid().0,
        n if n == api_v0::GETEGID => sys::sys_getegid().0,
        n if n == api_v0::SETSID => sys::sys_setsid().0,
        n if n == api_v0::GETSID => sys::sys_getsid(syscall_args).0,
        n if n == api_v0::GETGROUPS => sys::sys_getgroups(syscall_args).0,
        n if n == api_v0::SYSINFO => sys::sys_sysinfo(syscall_args).0,
        n if n == api_v0::SETUID => sys::sys_setuid(syscall_args).0,
        n if n == api_v0::SETGID => sys::sys_setgid(syscall_args).0,
        n if n == api_v0::SETREUID => sys::sys_setreuid(syscall_args).0,
        n if n == api_v0::SETREGID => sys::sys_setregid(syscall_args).0,
        n if n == api_v0::SETRESUID => sys::sys_setresuid(syscall_args).0,
        n if n == api_v0::SETRESGID => sys::sys_setresgid(syscall_args).0,
        n if n == api_v0::GETRESUID => sys::sys_getresuid(syscall_args).0,
        n if n == api_v0::GETRESGID => sys::sys_getresgid(syscall_args).0,
        n if n == api_v0::TIMES => sys::sys_times(syscall_args).0,
        n if n == api_v0::SETPGID => sys::sys_setpgid(syscall_args).0,
        n if n == api_v0::GETPGID => sys::sys_getpgid(syscall_args).0,
        n if n == api_v0::SETPRIORITY => sys::sys_setpriority(syscall_args).0,
        n if n == api_v0::GETPRIORITY => sys::sys_getpriority(syscall_args).0,
        n if n == api_v0::WAITPID => sys::sys_waitpid(syscall_args).0,
        n if n == api_v0::WAITID => sys::sys_waitid(syscall_args).0,
        n if n == api_v0::KILL => sys::sys_kill(syscall_args).0,
        n if n == api_v0::NANOSLEEP => sys::sys_nanosleep(syscall_args).0,
        n if n == api_v0::UNAME => sys::sys_uname(syscall_args).0,
        n if n == api_v0::SYSLOG => sys::sys_syslog(syscall_args).0,
        n if n == api_v0::PRCTL => sys::sys_prctl(syscall_args).0,
        n if n == api_v0::CAPGET => sys::sys_capget(syscall_args).0,
        n if n == api_v0::CAPSET => sys::sys_capset(syscall_args).0,
        n if n == api_v0::GETCWD => sys::sys_getcwd(syscall_args).0,
        n if n == api_v0::CHDIR => sys::sys_chdir(syscall_args).0,
        n if n == api_v0::FUTEX => sys::sys_futex(syscall_args).0,
        n if n == api_v0::SIGALTSTACK => sys::sys_sigaltstack(syscall_args).0,
        n if n == api_v0::RT_SIGACTION => sys::sys_rt_sigaction(syscall_args).0,
        n if n == api_v0::RT_SIGPROCMASK => sys::sys_rt_sigprocmask(syscall_args).0,
        n if n == api_v0::RT_SIGPENDING => sys::sys_rt_sigpending(syscall_args).0,
        n if n == api_v0::RT_SIGSUSPEND => sys::sys_rt_sigsuspend(syscall_args).0,
        n if n == api_v0::RT_SIGTIMEDWAIT => sys::sys_rt_sigtimedwait(syscall_args).0,
        n if n == api_v0::RT_SIGRETURN => {
            api_v0::UserRet::from_error(api_v0::ErrNo::ENOSYS).0
        }
        n if n == api_v0::TKILL => sys::sys_tkill(syscall_args).0,
        n if n == api_v0::TGKILL => sys::sys_tgkill(syscall_args).0,
        n if n == api_v0::SET_TID_ADDRESS => sys::sys_set_tid_address(syscall_args).0,
        n if n == api_v0::SET_ROBUST_LIST => sys::sys_set_robust_list(syscall_args).0,
        n if n == api_v0::GET_ROBUST_LIST => sys::sys_get_robust_list(syscall_args).0,
        n if n == api_v0::RSEQ => sys::sys_rseq(syscall_args).0,
        #[cfg(target_arch = "riscv64")]
        n if n == api_v0::RISCV_HWPROBE => sys::sys_riscv_hwprobe(syscall_args).0,
        n if n == api_v0::GETRANDOM => sys::sys_getrandom(syscall_args).0,
        n if n == api_v0::GETITIMER => sys::sys_getitimer(syscall_args).0,
        n if n == api_v0::SETITIMER => sys::sys_setitimer(syscall_args).0,
        n if n == api_v0::GETRLIMIT => sys::sys_getrlimit(syscall_args).0,
        n if n == api_v0::GETRUSAGE => sys::sys_getrusage(syscall_args).0,
        n if n == api_v0::SETRLIMIT => sys::sys_setrlimit(syscall_args).0,
        n if n == api_v0::UMASK => sys::sys_umask(syscall_args).0,
        n if n == api_v0::PRLIMIT64 => sys::sys_prlimit64(syscall_args).0,
        n if n == api_v0::SOCKET => sys::sys_socket(syscall_args).0,
        n if n == api_v0::SOCKETPAIR => sys::sys_socketpair(syscall_args).0,
        n if n == api_v0::BIND => sys::sys_bind(syscall_args).0,
        n if n == api_v0::LISTEN => sys::sys_listen(syscall_args).0,
        n if n == api_v0::ACCEPT => sys::sys_accept(syscall_args).0,
        n if n == api_v0::ACCEPT4 => sys::sys_accept4(syscall_args).0,
        n if n == api_v0::CONNECT => sys::sys_connect(syscall_args).0,
        n if n == api_v0::GETSOCKNAME => sys::sys_getsockname(syscall_args).0,
        n if n == api_v0::GETPEERNAME => sys::sys_getpeername(syscall_args).0,
        n if n == api_v0::SENDTO => sys::sys_sendto(syscall_args).0,
        n if n == api_v0::RECVFROM => sys::sys_recvfrom(syscall_args).0,
        n if n == api_v0::SENDMSG => sys::sys_sendmsg(syscall_args).0,
        n if n == api_v0::RECVMSG => sys::sys_recvmsg(syscall_args).0,
        n if n == api_v0::SENDMMSG => sys::sys_sendmmsg(syscall_args).0,
        n if n == api_v0::SETSOCKOPT => sys::sys_setsockopt(syscall_args).0,
        n if n == api_v0::GETSOCKOPT => sys::sys_getsockopt(syscall_args).0,
        n if n == api_v0::SHUTDOWN => sys::sys_shutdown(syscall_args).0,
        n if n == api_v0::PPOLL => sys::sys_ppoll(syscall_args).0,
        n if n == api_v0::PSELECT6 => sys::sys_pselect6(syscall_args).0,
        n if n == api_v0::POLL => sys::sys_poll(syscall_args).0,
        n if n == api_v0::SELECT => sys::sys_select(syscall_args).0,
        n if n == api_v0::EPOLL_CREATE1 => sys::sys_epoll_create1(syscall_args).0,
        n if n == api_v0::EPOLL_CTL => sys::sys_epoll_ctl(syscall_args).0,
        n if n == api_v0::EPOLL_WAIT => sys::sys_epoll_wait(syscall_args).0,
        n if n == api_v0::EPOLL_PWAIT => sys::sys_epoll_pwait(syscall_args).0,
        n if n == api_v0::EPOLL_PWAIT2 => sys::sys_epoll_pwait2(syscall_args).0,
        n if n == api_v0::FSTATAT => sys::sys_fstatat(syscall_args).0,
        n if n == api_v0::STATX => sys::sys_statx(syscall_args).0,
        n if n == api_v0::SCHED_SETATTR => sys::sys_sched_setattr(syscall_args).0,
        n if n == api_v0::SCHED_GETATTR => sys::sys_sched_getattr(syscall_args).0,
        n if n == api_v0::SCHED_RR_GET_INTERVAL => sys::sys_sched_rr_get_interval(syscall_args).0,
        n if n == api_v0::FACESSAT2 => sys::sys_faccessat2(syscall_args).0,
        n if n == api_v0::ADJTIMEX => sys::sys_adjtimex(syscall_args).0,
        n if n == api_v0::CLOCK_ADJTIME => sys::sys_clock_adjtime(syscall_args).0,
        n if n == api_v0::ACCT => sys::sys_acct(syscall_args).0,
        n if n == api_v0::CLOSE_RANGE => sys::sys_close_range(syscall_args).0,
        n if n == api_v0::SETGROUPS => sys::sys_setgroups(syscall_args).0,
        n if n == api_v0::FSTATFS => sys::sys_fstatfs(syscall_args).0,
        n if n == api_v0::LINKAT => sys::sys_linkat(syscall_args).0,
        n if n == api_v0::MKNODAT => sys::sys_mknodat(syscall_args).0,
        n if n == api_v0::SETXATTR => sys::sys_setxattr(syscall_args).0,
        n if n == api_v0::LSETXATTR => sys::sys_lsetxattr(syscall_args).0,
        n if n == api_v0::FSETXATTR => sys::sys_fsetxattr(syscall_args).0,
        n if n == api_v0::GETXATTR => sys::sys_getxattr(syscall_args).0,
        n if n == api_v0::LGETXATTR => sys::sys_lgetxattr(syscall_args).0,
        n if n == api_v0::FGETXATTR => sys::sys_fgetxattr(syscall_args).0,
        n if n == api_v0::LISTXATTR => sys::sys_listxattr(syscall_args).0,
        n if n == api_v0::LLISTXATTR => sys::sys_llistxattr(syscall_args).0,
        n if n == api_v0::FLISTXATTR => sys::sys_flistxattr(syscall_args).0,
        n if n == api_v0::REMOVEXATTR => sys::sys_removexattr(syscall_args).0,
        n if n == api_v0::LREMOVEXATTR => sys::sys_lremovexattr(syscall_args).0,
        n if n == api_v0::FREMOVEXATTR => sys::sys_fremovexattr(syscall_args).0,
        _ => api_v0::UserRet::from_error(api_v0::ErrNo::ENOSYS).0,
    }
}

/// EINTR 后可重启 syscall。
#[inline]
// 本方法代码由AI完成
pub fn is_restartable_syscall_nr(syscall_nr : usize) -> bool {
    syscall_nr == api_v0::READ ||
    syscall_nr == api_v0::READV ||
    syscall_nr == api_v0::WRITE ||
    syscall_nr == api_v0::WRITEV ||
    syscall_nr == api_v0::WAITPID ||
    syscall_nr == api_v0::WAITID ||
    syscall_nr == api_v0::ACCEPT4 ||
    syscall_nr == api_v0::CONNECT ||
    syscall_nr == api_v0::SENDTO ||
    syscall_nr == api_v0::RECVFROM ||
    syscall_nr == api_v0::SENDMSG ||
    syscall_nr == api_v0::RECVMSG ||
    syscall_nr == api_v0::SENDMMSG
}
