[package]
name = "wateros-network-impl-smoltcp"
version = "0.1.0"
edition = "2024"

[dependencies]
api-v0 = { path = "../../network-api/api-v0", package = "wateros-network-api-v0", default-features = false }
driver-network = { path = "../../../wateros-driver/driver-network", package = "wateros-driver-network", default-features = false, features = [ "api-v0" ] }
smoltcp = { version = "=0.12.0", default-features = false, features = [
    "alloc",
    "log",
    "medium-ethernet",
    "proto-ipv4",
    "socket-tcp",
    "socket-udp",
    "socket-icmp",
] }
log = "0.4.29"
arch = { path = "../../../wateros-platform/platform-arch", package = "wateros-platform-arch", default-features = false, features = [ "api-v0" ] }
debug = { path = "../../../wateros-debug", package = "wateros-debug", default-features = false }

[features]
self_test = []
ipv6 = [ "smoltcp/iface-max-addr-count-4", "smoltcp/proto-ipv6" ]
