[package]
    name = "wateros-task-impl-core"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    abi = { path = "../../../wateros-abi/", package = "wateros-abi", default-features = true }
    api-v0 = { path = "../../task-api/api-v0/", package = "wateros-task-api-v0", default-features = true }
    arch = { path = "../../../wateros-platform/platform-arch/", package = "wateros-platform-arch", default-features = false }

[features]
    api-v0 = [  ]
    default = [ "impl-riscv64" ]
    impl-loongarch64 = [ "arch/api-v0", "arch/impl-loongarch64" ]
    impl-riscv64 = [ "arch/api-v0", "arch/impl-riscv64" ]
