[package]
    name = "wateros-platform-impl-qemu-riscv64-opensbi"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "../../platform-api/api-v0/", package = "wateros-platform-api-v0", default-features = true }
base = { path = "../../../wateros-base/", package = "wateros-base", default-features = true }
config = { path = "../../../wateros-base/base-config/", package = "wateros-base-config" }
    sbi = { version = "0.0.3", package = "sbi-rt" }
    fdt = { version = "0.1.5" }

[features]
    api-v0 = [  ]
    default = [ "api-v0" ]
