[package]
name = "wateros-driver-impl-loongson2k1000la"
version = "0.1.0"
edition = "2024"

[dependencies]
api-v0 = { path = "../../driver-api/api-v0", package = "wateros-driver-api-v0" }
common = { path = "../impl-common", package = "wateros-driver-impl-common" }
dw-mmc = { path = "../../driver-block/block-impl/impl-dw-mmc", package = "wateros-driver-block-impl-dw-mmc" }
fdt = "0.1.5"
log = "0.4.29"
spin = "0.10.0"
mm-api = { path = "../../../wateros-mm/mm-api/api-v0", package = "wateros-mm-api-v0" }
character = { path = "../../driver-character", package = "wateros-driver-character", default-features = false, optional = true, features = [
    "api-v0",
    "impl-uart-16550",
] }
fs = { path = "../../../wateros-fs", package = "wateros-fs", default-features = true, optional = true }

[target.'cfg(target_arch = "loongarch64")'.dependencies]
platform = { path = "../../../wateros-platform", package = "wateros-platform", default-features = false, features = ["impl-loongson2k1000la"] }
frame-allocator = { path = "../../../wateros-mm/mm-frame-alloctor", package = "wateros-mm-frame-alloctor" }

[features]
api-v0 = []
default = ["api-v0"]
uart-16550 = ["dep:character", "dep:fs"]
