[package]
    name = "wateros-mm-api-v0"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    frame_alloctor_api_v0 = { path = "../../mm-frame-alloctor/frame-alloctor-api/api-v0/", package = "wateros-mm-frame-alloctor-api-v0", default-features = true }
log = { version = "0.4.29" }
spin = "0.10"
