[workspace]
    members = [
        "./fs-api/api-v0/",
        "./fs-devfs/",
        "./fs-devfs/devfs-api/api-v0/",
        "./fs-devfs/devfs-impl/impl-dummy/",
        "./fs-devfs/devfs-impl/impl-kernel/",
        "./fs-impl/impl-devfs/",
        "./fs-impl/impl-dummy/",
        "./fs-impl/impl-ext4/",
        "./fs-rootfs/",
        "./fs-rootfs/rootfs-api/api-v0/",
        "./fs-rootfs/rootfs-impl/impl-dummy/",
        "./fs-rootfs/rootfs-impl/impl-kernel/",
        "./fs-procfs/",
        "./fs-procfs/procfs-api/api-v0/",
        "./fs-procfs/procfs-impl/impl-dummy/",
        "./fs-procfs/procfs-impl/impl-kernel/",
    ]
[package]
    name = "wateros-fs"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "./fs-api/api-v0/", package = "wateros-fs-api-v0", default-features = true }
    devfs = { path = "./fs-devfs/", package = "wateros-fs-devfs", default-features = true }
    procfs = { path = "./fs-procfs/", package = "wateros-fs-procfs", default-features = true }
    rootfs = { path = "./fs-rootfs/", package = "wateros-fs-rootfs", default-features = true }
    impl-dummy = { path = "./fs-impl/impl-dummy/", package = "wateros-fs-impl-dummy", default-features = true }
    impl-devfs = { path = "./fs-impl/impl-devfs/", package = "wateros-fs-impl-devfs", default-features = true }
    impl-ext4 = { path = "./fs-impl/impl-ext4/", package = "wateros-fs-impl-ext4", default-features = true, optional = true }
    logging = { path = "../wateros-runtime/runtime-logging", package = "wateros-runtime-logging", default-features = true }
    spin = "0.10.0"

[features]
    api-v0 = [
        "devfs/api-v0",
        "procfs/api-v0",
        "impl-dummy/api-v0",
        "impl-ext4?/api-v0",
        "rootfs/api-v0",
    ]
    default = [ "api-v0", "impl-devfs", "impl-ext4" ]
    impl-devfs = [  ]
    impl-dummy = [  ]
    impl-ext4 = [ "dep:impl-ext4" ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
