#!/bin/sh

# 定义 ANSI 颜色
COLOR_ANSI_RED="\033[31m"
COLOR_ANSI_GREEN="\033[32m"
COLOR_ANSI_YELLOW="\033[33m"
COLOR_ANSI_BLUE="\033[34m"
COLOR_ANSI_PURPLE="\033[35m"
COLOR_ANSI_CYAN="\033[36m"
COLOR_ANSI_WHITE="\033[37m"
COLOR_ANSI_CLEAR="\033[0m"

# TRACE 函数
trace() {
  printf "%b" "${COLOR_ANSI_WHITE}[SCRITP]${COLOR_ANSI_CLEAR}${COLOR_ANSI_CYAN}\t[TRACE]\t$1${COLOR_ANSI_CLEAR}\n"
}

# INFO 函数
info() {
  printf "%b" "${COLOR_ANSI_WHITE}[SCRITP]${COLOR_ANSI_CLEAR}${COLOR_ANSI_GREEN}\t[INFO]\t$1${COLOR_ANSI_CLEAR}\n"
}

# WARNING 函数
warning() {
  printf "%b" "${COLOR_ANSI_WHITE}[SCRITP]${COLOR_ANSI_CLEAR}${COLOR_ANSI_YELLOW}\t[WARNING]\t$1${COLOR_ANSI_CLEAR}\n"
}

# ERROR 函数
error() {
  printf "%b" "${COLOR_ANSI_WHITE}[SCRITP]${COLOR_ANSI_CLEAR}${COLOR_ANSI_RED}\t[ERROR]\t$1 错误代码:$2${COLOR_ANSI_CLEAR}\n"
  exit $2
}

debug() {
  printf "%b" "${COLOR_ANSI_WHITE}[SCRITP]${COLOR_ANSI_CLEAR}${COLOR_ANSI_BLUE}\t[DEBUG]\t$1${COLOR_ANSI_CLEAR}\n"
}
