[package]
    name = "wateros-syscall-api-v0"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    abi = { path = "../../../wateros-abi/", package = "wateros-abi", default-features = false }

[features]
    api-v0 = [ "abi/api-v0" ]
    default = [ "api-v0" ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
