[package]
    name = "wateros-syscall-api-v0"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    config = { path = "../../../wateros-base/base-config/", package = "wateros-base-config", default-features = true }

[features]
    api-v0 = [  ]
    default = [ "api-v0" ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
