[package]
name = "wateros-driver-input-impl-virtio-pci"
version = "0.1.0"
edition = "2024"

[dependencies]
api-v0 = { path = "../../input-api/api-v0", package = "wateros-driver-input-api-v0" }
driver-api = { path = "../../../driver-api/api-v0", package = "wateros-driver-api-v0" }
driver-common = { path = "../../../driver-impl/impl-common", package = "wateros-driver-impl-common" }
frame-alloctor = { path = "../../../../wateros-mm/mm-frame-alloctor", package = "wateros-mm-frame-alloctor" }
mm-api = { path = "../../../../wateros-mm/mm-api/api-v0", package = "wateros-mm-api-v0" }
virtio-drivers = "=0.12.0"

[features]
default = []
