[package]
    name = "wateros-driver-network-impl-virtio-pci"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "../../network-api/api-v0/", package = "wateros-driver-network-api-v0", default-features = true }
    driver-api = { path = "../../../driver-api/api-v0", package = "wateros-driver-api-v0", default-features = true }
    driver-common = { path = "../../../driver-impl/impl-common", package = "wateros-driver-impl-common", default-features = true }
    frame_alloctor = { path = "../../../../wateros-mm/mm-frame-alloctor", package = "wateros-mm-frame-alloctor", default-features = true }
    logging = { path = "../../../../wateros-runtime/runtime-logging", package = "wateros-runtime-logging", default-features = true }
    mm-api = { path = "../../../../wateros-mm/mm-api/api-v0", package = "wateros-mm-api-v0", default-features = true }
    virtio-drivers = "=0.12.0"

[features]
    api-v0 = [  ]
    default = [ "api-v0" ]
