[workspace]
    members = [
        "./ipc-api/api-v0/",
        "./ipc-impl/impl-dummy/",
        "./ipc-waitqueue/",
    ]
[package]
    name = "wateros-ipc"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "./ipc-api/api-v0/", package = "wateros-ipc-api-v0", default-features = true }
    impl-dummy = { path = "./ipc-impl/impl-dummy/", package = "wateros-ipc-impl-dummy", default-features = true }
    waitqueue = { path = "./ipc-waitqueue/", package = "ipc-waitqueue", default-features = true }

[features]
    api-v0 = [ "impl-dummy/api-v0" ]
    default = [ "api-v0", "impl-dummy" ]
    impl-dummy = [  ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
