[workspace]
    members = [
        "./ipc-api/api-v0/",
        "./ipc-impl/impl-dummy/",
        "./ipc-waitqueue/",
        "./ipc-waitqueue/waitqueue-api/api-v0/",
        "./ipc-waitqueue/waitqueue-impl/impl-task/",
        "./ipc-futex/",
        "./ipc-futex/futex-api/api-v0/",
        "./ipc-futex/futex-impl/impl-dummy/",
        "./ipc-futex/futex-impl/impl-task/",
    ]
[package]
    name = "wateros-ipc"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "./ipc-api/api-v0/", package = "wateros-ipc-api-v0", default-features = true }
    impl-dummy = { path = "./ipc-impl/impl-dummy/", package = "wateros-ipc-impl-dummy", default-features = true }
    futex = { path = "./ipc-futex/", package = "ipc-futex", default-features = false, optional = true }
    pipe = { path = "./ipc-pipe/", package = "ipc-pipe", default-features = false, optional = true }
    waitqueue = { path = "./ipc-waitqueue/", package = "ipc-waitqueue", default-features = true }

[features]
    api-v0 = [ "impl-dummy/api-v0" ]
    default = [ "api-v0", "impl-dummy" ]
    futex = [ "dep:futex", "futex/api-v0", "futex/impl-task" ]
    impl-dummy = [  ]
    impl-loongarch64 = [
        "futex?/impl-task",
        "futex?/impl-loongarch64",
        "pipe?/impl-loongarch64",
        "waitqueue/impl-loongarch64",
    ]
    impl-riscv64 = [
        "futex?/impl-task",
        "futex?/impl-riscv64",
        "pipe?/impl-riscv64",
        "waitqueue/impl-riscv64",
    ]
    pipe = [ "dep:pipe", "pipe/api-v0", "pipe/impl-ringbuf" ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
