[package]
    name = "wateros-runtime-panic"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    platform = { path = "../../wateros-platform/", package = "wateros-platform", default-features = false }
    console = { path = "../runtime-console/", package = "wateros-runtime-console", default-features = false }

[features]
    default = [  ]
    impl-dummy = [ "console/impl-dummy", "platform/impl-dummy" ]
    impl-platform-console = [
        "console/impl-platform-console",
        "platform/api-v0",
    ]
