[package]
    name = "wateros-runtime-panic"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    firmware = { path = "../../wateros-platform/platform-firmware/", package = "wateros-platform-firmware", default-features = true }
    console = {path = "../runtime-console/", package = "wateros-runtime-console"}
