[package]
name = "wateros-driver-impl-jh7110-visionfive2"
version = "0.1.0"
edition = "2024"

[dependencies]
api-v0 = { path = "../../driver-api/api-v0", package = "wateros-driver-api-v0" }
dw-mmc = { path = "../../driver-block/block-impl/impl-dw-mmc", package = "wateros-driver-block-impl-dw-mmc" }
character = { path = "../../driver-character", package = "wateros-driver-character", features = [
    "impl-null-stub",
    "impl-rtc-stub",
    "impl-uart-16550",
] }
common = { path = "../impl-common", package = "wateros-driver-impl-common" }
fdt = "0.1.5"
log = "0.4.29"
spin = "0.10.0"

[target.'cfg(target_arch = "riscv64")'.dependencies]
platform = { path = "../../../wateros-platform", package = "wateros-platform", default-features = false, features = [ "impl-jh7110-visionfive2" ] }

[features]
api-v0 = []
default = [ "api-v0" ]
