[workspace]
    members = [
        "./task-api/api-v0/",
        "./task-impl/impl-core/",
        "./task-scheduler/",
        "./task-scheduler/scheduler-api/api-v0/",
        "./task-scheduler/scheduler-impl/impl-multi-class/",
    ]
[package]
    name = "wateros-task"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    log = { version = "0.4" }
    api-v0 = { path = "./task-api/api-v0/", package = "wateros-task-api-v0", default-features = true }
    arch = { path = "../wateros-platform/platform-arch/", package = "wateros-platform-arch", default-features = false }
    impl-core = { path = "./task-impl/impl-core/", package = "wateros-task-impl-core", default-features = false }
    mm-api = { path = "../wateros-mm/mm-api/api-v0/", package = "wateros-mm-api-v0", default-features = true }
    scheduler = { path = "./task-scheduler/", package = "wateros-task-scheduler", default-features = false }
    base = { path = "../wateros-base", package = "wateros-base", default-features = false }


[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
