[workspace]
    members = [
        "./task-api/api-v0/",
        "./task-impl/impl-core/",
        "./task-scheduler/",
        "./task-scheduler/scheduler-api/api-v0/",
        "./task-scheduler/scheduler-impl/impl-multi-class/",
        "./task-scheduler/scheduler-impl/impl-round-robin/",
    ]
[package]
    name = "wateros-task"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "./task-api/api-v0/", package = "wateros-task-api-v0", default-features = true }
    arch = { path = "../wateros-platform/platform-arch/", package = "wateros-platform-arch", default-features = false }
    impl-core = { path = "./task-impl/impl-core/", package = "wateros-task-impl-core", default-features = false }
    mm-api = { path = "../wateros-mm/mm-api/api-v0/", package = "wateros-mm-api-v0", default-features = true }
    scheduler = { path = "./task-scheduler/", package = "wateros-task-scheduler", default-features = false }

[features]
    api-v0 = [ "impl-core/api-v0", "scheduler/api-v0" ]
    default = [ "api-v0", "impl-core", "impl-multi-class" ]
    impl-core = [  ]
    impl-multi-class = [ "scheduler/impl-multi-class" ]
    impl-round-robin = [ "scheduler/impl-round-robin" ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
