[package]
    name = "wateros-fs-impl-ext4"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "../../fs-api/api-v0/", package = "wateros-fs-api-v0", default-features = true }
    driver-block-api-v0 = { path = "../../../wateros-driver/driver-block/block-api/api-v0", package = "wateros-driver-block-api-v0", default-features = true }
    ext4-view = { version = "0.9.3", default-features = true }
    ext4plus = { version = "0.1.0-beta.3", default-features = true, features = [ "multi-threaded", "sync" ] }
    logging = { path = "../../../wateros-runtime/runtime-logging", package = "wateros-runtime-logging", default-features = true }
    spin = "0.10.0"

[features]
    api-v0 = [  ]
    default = [ "api-v0" ]
