[workspace]
    members = [
        "./runtime-console/console-api/api-v0/",
        "./runtime-console/console-impl/impl-dummy/",
        "./runtime-console/console-impl/impl-firmware-opensbi/",
        "./runtime-logging/",
        "./runtime-panic/",
        "runtime-console",
        "runtime-heap-allocator",
    ]
[package]
    name = "wateros-runtime"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    panic = { path = "./runtime-panic/", package = "wateros-runtime-panic", default-features = true }
    console = { path = "./runtime-console/", package = "wateros-runtime-console", default-features = false }
    logging = { path = "./runtime-logging/", package = "wateros-runtime-logging", default-features = false }
    heap-allocator = { path = "./runtime-heap-allocator/", package = "wateros-runtime-heap-allocator", default-features = true }

[features]
    default = []
    impl-debug = [ "logging/impl-debug" ]
    impl-dummy = [ "console/impl-dummy", "logging/impl-dummy" ]
    impl-error = [ "logging/impl-error" ]
    impl-firmware-console = [
        "console/impl-firmware-console",
        "logging/impl-firmware-console",
    ]
    impl-firmware-opensbi = [
        "console/impl-firmware-opensbi",
        "logging/impl-firmware-opensbi",
    ]
    impl-info = [ "logging/impl-info" ]
    impl-trace = [ "logging/impl-trace" ]
    impl-warn = [ "logging/impl-warn" ]
