[package]
    name = "wateros-driver-network"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "./network-api/api-v0/", package = "wateros-driver-network-api-v0", default-features = true }
    driver-api = { path = "../driver-api/api-v0/", package = "wateros-driver-api-v0", default-features = true }
    impl-dummy = { path = "./network-impl/impl-dummy/", package = "wateros-driver-network-impl-dummy", default-features = true }
    impl-virtio-mmio = { path = "./network-impl/impl-virtio-mmio/", package = "wateros-driver-network-impl-virtio-mmio", default-features = true, optional = true }
    impl-smoltcp = { path = "./network-impl/impl-smoltcp/", package = "wateros-driver-network-impl-smoltcp", default-features = true, optional = true }
    log = { version = "0.4.29" }
    smoltcp = { version = "0.13", default-features = false, features = [
        "alloc",
        "log",
        "medium-ethernet",
        "proto-ipv4",
        "socket-tcp",
        "socket-udp",
    ], optional = true }
    spin = "0.10.0"
    vfs-api = { path = "../../wateros-vfs/vfs-api/api-v0/", package = "wateros-vfs-api-v0", default-features = true, optional = true }

[features]
    api-v0 = [ "impl-dummy/api-v0" ]
    default = [ "api-v0", "impl-dummy", "impl-smoltcp", "impl-virtio-mmio" ]
    impl-dummy = [  ]
    impl-smoltcp = [ "dep:impl-smoltcp", "dep:smoltcp", "dep:vfs-api" ]
    impl-virtio-mmio = [ "dep:impl-virtio-mmio" ]
