# WaterOS LoongArch64 config.conf
# 规则：未注释行 = 启用；以 # 开头 = 禁用。
# 用途：供 `make la_check` / `make kernel-la` 生成 Cargo features。
# 注意：本文件不用于 apply_features，不写回 Cargo.toml 默认 feature。

wateros:
  # manifest: Cargo.toml
  # impl-sv39
  qemu-loongarch64-virt
  # qemu-riscv64-opensbi
  wateros-abi:
    # manifest: components/wateros-abi/Cargo.toml
    api-v0
    # impl-dummy
    # impl-linux-generic64
    impl-linux-loongarch64
    # impl-linux-riscv64
  wateros-platform:
    # manifest: components/wateros-platform/Cargo.toml
    api-v0
    # impl-dummy
    impl-qemu-loongarch64-virt
    # impl-qemu-riscv64-opensbi
    wateros-platform-arch:
      # manifest: components/wateros-platform/platform-arch/Cargo.toml
      api-v0
      # impl-dummy
      impl-loongarch64
      # impl-riscv64
    wateros-platform-firmware:
      # manifest: components/wateros-platform/platform-firmware/Cargo.toml
      api-v0
      # impl-dummy
      impl-qemu-loongarch64-uart16550
      # impl-riscv64-opensbi
  wateros-runtime:
    # manifest: components/wateros-runtime/Cargo.toml
    impl-debug
    # impl-dummy
    # impl-error
    impl-firmware-console
    # impl-firmware-opensbi
    # impl-info
    # impl-trace
    # impl-warn
    wateros-runtime-console:
      # manifest: components/wateros-runtime/runtime-console/Cargo.toml
      api-v0
      # impl-dummy
      impl-firmware-console
      # impl-firmware-opensbi
    wateros-runtime-logging:
      # manifest: components/wateros-runtime/runtime-logging/Cargo.toml
      impl-debug
      # impl-dummy
      # impl-error
      impl-firmware-console
      # impl-firmware-opensbi
      # impl-info
      # impl-trace
      # impl-warn
    wateros-runtime-panic:
      # manifest: components/wateros-runtime/runtime-panic/Cargo.toml
      # impl-dummy
      impl-firmware-console
      # impl-firmware-opensbi
  wateros-syscall:
    # manifest: components/wateros-syscall/Cargo.toml
    impl-loongarch64
    # impl-riscv64
  wateros-task:
    # manifest: components/wateros-task/Cargo.toml
    api-v0
    impl-core
    impl-loongarch64
    # impl-riscv64
    impl-round-robin
    wateros-task-scheduler:
      # manifest: components/wateros-task/task-scheduler/Cargo.toml
      api-v0
      impl-round-robin
