[package]
    name = "ipc-pipe"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "./pipe-api/api-v0/", package = "wateros-ipc-pipe-api-v0", default-features = true }
    impl-ringbuf = { path = "./pipe-impl/impl-ringbuf/", package = "wateros-ipc-pipe-impl-ringbuf", default-features = true }

[features]
    api-v0 = [ "impl-ringbuf/api-v0" ]
    default = [ "api-v0" ]
    impl-loongarch64 = [ "impl-ringbuf/impl-loongarch64" ]
    impl-ringbuf = [  ]
    impl-riscv64 = [ "impl-ringbuf/impl-riscv64" ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
