[package]
    name = "wateros-driver-impl-qemu-riscv64-opensbi"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    fdt = "0.1.5"
    logging = { path = "../../../wateros-runtime/runtime-logging", package = "wateros-runtime-logging", default-features = true }
    spin = "0.10.0"
    wateros-driver-character-api-v0 = { path = "../../driver-character/character-api/api-v0", package = "wateros-driver-character-api-v0", default-features = true }
    api-v0 = { path = "../../driver-api/api-v0", package = "wateros-driver-api-v0", default-features = true }
    block = { path = "../../driver-block", package = "wateros-driver-block", default-features = true, features = [
        "api-v0",
        "impl-virtio-mmio",
    ] }
    network = { path = "../../driver-network", package = "wateros-driver-network", default-features = true, features = [
        "api-v0",
        "impl-virtio-mmio",
    ] }
    fs = { path = "../../../wateros-fs", package = "wateros-fs", default-features = true }
    wateros-base-config = { path = "../../../wateros-base/base-config", package = "wateros-base-config" }

[features]
    api-v0 = [  ]
    default = [ "api-v0" ]
    block-cache = [ "block/impl-block-cache" ]
