[package]
    name = "wateros-mm-impl-sv39"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "../../mm-api/api-v0/", package = "wateros-mm-api-v0", default-features = true }
    impl-common = { path = "../common/", package = "wateros-mm-impl-common", default-features = true }
    frame-alloctor = { path = "../../mm-frame-alloctor", package = "wateros-mm-frame-alloctor", default-features = true, features = [
        "impl-stack",
    ] }
    fs = { package = "wateros-fs", path = "../../../wateros-fs", default-features = true }
    vfs = { package = "wateros-vfs", path = "../../../wateros-vfs", default-features = false, features = [
        "bridge-fs-api",
    ], optional = true }
    platform = { package = "wateros-platform", path = "../../../wateros-platform", default-features = true }
    runtime = { package = "wateros-runtime", path = "../../../wateros-runtime", default-features = true }
    wateros-base = { path = "../../../wateros-base", package = "wateros-base", default-features = true }
    wateros-base-config = { path = "../../../wateros-base/base-config", package = "wateros-base-config" }
    log = { version = "0.4.29" }

[features]
    api-v0 = [  ]
    default = [ "api-v0" ]
    vfs-root-read = [ "dep:vfs" ]
