[workspace]
    members = [
        "./vfs-api/api-v0/",
        "./vfs-impl/impl-dummy/",
        "./vfs-impl/impl-fd-session/",
        "./vfs-impl/impl-page-cache/",
    ]
[package]
    name = "wateros-vfs"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "./vfs-api/api-v0/", package = "wateros-vfs-api-v0", default-features = true }
    base = { path = "../wateros-base/", package = "wateros-base", default-features = true, optional = true }
    impl-dummy = { path = "./vfs-impl/impl-dummy/", package = "wateros-vfs-impl-dummy", default-features = true }
    impl_fd_session = { path = "./vfs-impl/impl-fd-session/", package = "wateros-vfs-impl-fd-session", default-features = false, optional = true }
    impl_fs_bridge = { path = "./vfs-impl/impl-fs-bridge/", package = "wateros-vfs-impl-fs-bridge", default-features = true, optional = true }
    fs = { path = "../wateros-fs/", package = "wateros-fs", default-features = true, optional = true }
    log = { version = "0.4.29" }
    task = { path = "../wateros-task/", package = "wateros-task", default-features = false, optional = true }
    arch = { path = "../wateros-platform/platform-arch/", package = "wateros-platform-arch", default-features = false, features = [ "api-v0" ], optional = true }
    debug = { path = "../wateros-debug/", package = "wateros-debug", default-features = false, optional = true }

[features]
    api-v0 = [ "impl-dummy/api-v0", "impl_fs_bridge?/api-v0" ]
    bridge-fs-api = [
        "dep:fs",
        "dep:impl_fs_bridge",
        "impl_fs_bridge/bridge-fs-api",
    ]
    default = [ "api-v0", "bridge-fs-api", "impl-fd-session" ]
    impl-dummy = [  ]
    impl-fd-session = [
        "dep:base",
        "dep:impl_fd_session",
        "dep:task",
        "dep:arch",
        "dep:debug",
        "impl_fd_session/impl-fd-session",
    ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
