[package]
    name = "wateros-ipc-futex-impl-task"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "../../futex-api/api-v0/", package = "wateros-ipc-futex-api-v0", default-features = true }
    ipc-waitqueue = { path = "../../../ipc-waitqueue/", package = "ipc-waitqueue", default-features = true }
    log = "0.4"
    spin = "0.10.0"
    task-api = { path = "../../../../wateros-task/task-api/api-v0/", package = "wateros-task-api-v0", default-features = true }

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
