[package]
    name = "wateros-runtime-heap-allocator"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    linked_list_allocator = { version = "0.10.6" }
    config = { path = "../../wateros-base/base-config/", package = "wateros-base-config" }
[features]
    default = [ "impl-linked-list-allocator" ]
    impl-linked-list-allocator = [  ]
