[package]
    name = "wateros-runtime-heap-allocator"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    linked_list_allocator = { version = "0.10.6", optional = true }
    rlsf = { version = "0.2.2", default-features = false }
    spin = { version = "0.10.0", default-features = false, features = [
        "mutex",
        "spin_mutex",
    ] }
    config = { path = "../../wateros-base/base-config/", package = "wateros-base-config" }
    base = { path = "../../wateros-base/", package = "wateros-base" }
    arch = { path = "../../wateros-platform/platform-arch/", package = "wateros-platform-arch", default-features = false, features = [
        "api-v0",
    ] }
    log = { version = "0.4" }
[features]
    self_test = [  ]
    impl-riscv64 = [ "arch/impl-riscv64" ]
    impl-loongarch64 = [ "arch/impl-loongarch64" ]
    default = [ "impl-tlsf", "impl-riscv64" ]
    impl-linked-list-allocator = [ "dep:linked_list_allocator" ]
    impl-tlsf = [  ]
    stress-on-init = [  ]
    tlsf-diagnostics = [  ]
