[package]
    name = "wateros-driver-network-impl-smoltcp"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "../../network-api/api-v0/", package = "wateros-driver-network-api-v0", default-features = true }
    log = "0.4.29"
    smoltcp = { version = "0.13", default-features = false, features = [
        "alloc",
        "log",
        "medium-ethernet",
        "proto-ipv4",
        "socket-raw",
        "socket-icmp",
        "socket-udp",
        "socket-tcp",
    ] }

[features]
    api-v0 = [  ]
    default = [ "api-v0" ]
