[package]
    name = "ipc-shm"
    version = "0.1.0"
    edition = "2024"

[dependencies]
api-v0 = { path = "./shm-api/api-v0/", package = "wateros-ipc-shm-api-v0", default-features = true, optional = true }
impl-frame = { path = "./shm-impl/impl-frame/", package = "wateros-ipc-shm-impl-frame", default-features = false, optional = true }

[features]
api-v0 = [ "dep:api-v0", "impl-frame?/api-v0" ]
default = [ "impl-frame" ]
impl-frame = [ "api-v0", "dep:impl-frame", "impl-frame/impl-frame" ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
