[package]
    name = "wateros-runtime-console-impl-platform-console"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "../../console-api/api-v0/", package = "wateros-runtime-console-api-v0" }
    platform = { path = "../../../../wateros-platform/", package = "wateros-platform", default-features = false, features = [
        "api-v0",
    ] }
[features]
    api-v0 = [  ]
    default = [  ]
