[package]
    name = "ipc-futex"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "./futex-api/api-v0/", package = "wateros-ipc-futex-api-v0", default-features = true }
    impl-dummy = { path = "./futex-impl/impl-dummy/", package = "wateros-ipc-futex-impl-dummy", default-features = false, optional = true }
    impl-task = { path = "./futex-impl/impl-task/", package = "wateros-ipc-futex-impl-task", default-features = false, optional = true }

[features]
    api-v0 = [
        "impl-dummy?/api-v0",
        "impl-task?/api-v0",
    ]
    default = [ "api-v0", "impl-task" ]
    impl-dummy = [ "dep:impl-dummy", "impl-dummy/api-v0" ]
    impl-loongarch64 = [ "impl-task", "impl-task/impl-loongarch64" ]
    impl-riscv64 = [ "impl-task", "impl-task/impl-riscv64" ]
    impl-task = [ "dep:impl-task", "impl-task/api-v0" ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
