[workspace]
    members = [
        "./driver-api/api-v0/",
        "./driver-block/",
        "./driver-block/block-api/api-v0/",
        "./driver-block/block-impl/impl-block-cache/",
        "./driver-block/block-impl/impl-dummy/",
        "./driver-block/block-impl/impl-virtio-mmio/",
        "./driver-block/block-impl/impl-virtio-pci/",
        "./driver-character/",
        "./driver-character/character-api/api-v0/",
        "./driver-character/character-impl/impl-dummy/",
        "./driver-character/character-impl/impl-null-stub/",
        "./driver-character/character-impl/impl-rtc-stub/",
        "./driver-character/character-impl/impl-uart-16550/",
        "./driver-display/",
        "./driver-display/display-api/api-v0/",
        "./driver-display/display-impl/impl-virtio-mmio/",
        "./driver-display/display-impl/impl-virtio-pci/",
        "./driver-input/",
        "./driver-input/input-api/api-v0/",
        "./driver-input/input-impl/impl-virtio-mmio/",
        "./driver-input/input-impl/impl-virtio-pci/",
        "./driver-impl/impl-dummy/",
        "./driver-impl/impl-common/",
        "./driver-impl/impl-qemu-loongarch64-virt/",
        "./driver-impl/impl-qemu-riscv64-virt/",
        "./driver-network/",
        "./driver-network/network-api/api-v0/",
        "./driver-network/network-impl/impl-dummy/",
        "./driver-network/network-impl/impl-virtio-mmio/",
        "./driver-network/network-impl/impl-virtio-pci/",
    ]
[package]
    name = "wateros-driver"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "./driver-api/api-v0/", package = "wateros-driver-api-v0", default-features = true }
    impl-dummy = { path = "./driver-impl/impl-dummy/", package = "wateros-driver-impl-dummy", default-features = true }
    impl-qemu-riscv64-virt = { path = "./driver-impl/impl-qemu-riscv64-virt/", package = "wateros-driver-impl-qemu-riscv64-virt", default-features = true, optional = true }
    impl-qemu-loongarch64-virt = { path = "./driver-impl/impl-qemu-loongarch64-virt/", package = "wateros-driver-impl-qemu-loongarch64-virt", default-features = true, optional = true }
    block = { path = "./driver-block/", package = "wateros-driver-block", default-features = true }
    character = { path = "./driver-character/", package = "wateros-driver-character", default-features = true, features = [
        "impl-null-stub",
        "impl-rtc-stub",
    ] }
    display = { path = "./driver-display/", package = "wateros-driver-display", default-features = true }
    input = { path = "./driver-input/", package = "wateros-driver-input", default-features = true }
    network = { path = "./driver-network/", package = "wateros-driver-network", default-features = true }
    wateros-base-config = { path = "../wateros-base/base-config", package = "wateros-base-config" }
    log = { version = "0.4.29" }

[features]
    api-v0 = [
        "block/api-v0",
        "character/api-v0",
        "display/api-v0",
        "input/api-v0",
        "impl-dummy/api-v0",
        "impl-qemu-loongarch64-virt?/api-v0",
        "impl-qemu-riscv64-virt?/api-v0",
        "network/api-v0",
    ]
    default = [ "api-v0" ]
    display = [
        "impl-qemu-loongarch64-virt?/display",
        "impl-qemu-riscv64-virt?/display",
    ]
    input = [
        "impl-qemu-loongarch64-virt?/input",
        "impl-qemu-riscv64-virt?/input",
    ]
    impl-block-cache = [
        "block/impl-block-cache",
        "impl-qemu-loongarch64-virt?/block-cache",
        "impl-qemu-riscv64-virt?/block-cache",
    ]
    block-interrupt-wait = [ "block/interrupt-wait" ]
    impl-dummy = [  ]
    impl-qemu-loongarch64-virt = [
        "dep:impl-qemu-loongarch64-virt",
        "block/impl-virtio-pci",
        "network/impl-virtio-pci",
    ]
    impl-qemu-riscv64-virt = [
        "dep:impl-qemu-riscv64-virt",
        "block/impl-virtio-mmio",
        "network/impl-virtio-mmio",
    ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
