[workspace]
    members = [
        "./driver-api/api-v0/",
        "./driver-block/",
        "./driver-block/block-api/api-v0/",
        "./driver-block/block-impl/impl-dummy/",
        "./driver-block/block-impl/impl-virtio-mmio/",
        "./driver-character/",
        "./driver-character/character-api/api-v0/",
        "./driver-character/character-impl/impl-dummy/",
        "./driver-impl/impl-dummy/",
        "./driver-impl/impl-qemu-riscv64-opensbi/",
        "./driver-network/",
        "./driver-network/network-api/api-v0/",
        "./driver-network/network-impl/impl-dummy/",
    ]
    exclude = [ "./driver-block/block-impl/impl-block-cache/" ]
[package]
    name = "wateros-driver"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "./driver-api/api-v0/", package = "wateros-driver-api-v0", default-features = true }
    impl-dummy = { path = "./driver-impl/impl-dummy/", package = "wateros-driver-impl-dummy", default-features = true }
    impl-qemu-riscv64-opensbi = { path = "./driver-impl/impl-qemu-riscv64-opensbi/", package = "wateros-driver-impl-qemu-riscv64-opensbi", default-features = true }
    block = { path = "./driver-block/", package = "wateros-driver-block", default-features = true }
    character = { path = "./driver-character/", package = "wateros-driver-character", default-features = true }
    network = { path = "./driver-network/", package = "wateros-driver-network", default-features = true }
    wateros-base-config = { path = "../wateros-base/base-config", package = "wateros-base-config" }
    log = { version = "0.4.29" }

[features]
    api-v0 = [
        "block/api-v0",
        "character/api-v0",
        "impl-dummy/api-v0",
        "impl-qemu-riscv64-opensbi/api-v0",
        "network/api-v0",
    ]
    default = [ "api-v0", "impl-qemu-riscv64-opensbi" ]
    impl-dummy = [  ]
    impl-qemu-riscv64-opensbi = [ "block/impl-virtio-mmio" ]
    impl-block-cache = [ "block/impl-block-cache", "impl-qemu-riscv64-opensbi/block-cache" ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
