[package]
    name = "wateros-syscall-impl-kernel"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "../../syscall-api/api-v0/", package = "wateros-syscall-api-v0", default-features = true }
    abi = { path = "../../../wateros-abi/", package = "wateros-abi", default-features = false }
    task = { path = "../../../wateros-task/", package = "wateros-task", default-features = false }
    ipc = { path = "../../../wateros-ipc/", package = "wateros-ipc", default-features = false, optional = true }
    cred = { path = "../../../wateros-cred/", package = "wateros-cred", default-features = false, optional = true }
    mm = { path = "../../../wateros-mm/", package = "wateros-mm", default-features = true, optional = true }
    vfs = { path = "../../../wateros-vfs/", package = "wateros-vfs", default-features = false, optional = true }
    driver = { path = "../../../wateros-driver/", package = "wateros-driver", default-features = false, optional = true }
    driver-network = { path = "../../../wateros-driver/driver-network/", package = "wateros-driver-network", default-features = false, optional = true }
    log = { version = "0.4.29" }
    smoltcp = { version = "0.13", default-features = false, optional = true }
    spin = "0.10.0"

[features]
    api-v0 = [ "abi/api-v0", "api-v0/api-v0", "fd-session" ]
    cred-session = [ "cred/api-v0", "cred/impl-root", "dep:cred" ]
    default = [ "api-v0" ]
    fd-session = [
        "cred-session",
        "dep:ipc",
        "dep:mm",
        "dep:vfs",
        "ipc/futex",
        "ipc/pipe",
        "mm/api-v0",
        "vfs/bridge-fs-api",
        "vfs/fd-session",
    ]
    impl-loongarch64 = [
        "abi/api-v0",
        "api-v0",
        "fd-session",
        "ipc/impl-loongarch64",
        "socket-net",
        "task/api-v0",
        "task/impl-core",
    ]
    impl-sv39 = []
    impl-riscv64 = [
        "abi/api-v0",
        "api-v0",
        "fd-session",
        "impl-sv39",
        "ipc/impl-riscv64",
        "socket-net",
        "task/api-v0",
        "task/impl-core",
    ]
    socket-net = [
        "dep:driver",
        "dep:driver-network",
        "dep:smoltcp",
        "driver-network/impl-smoltcp",
        "driver-network/impl-virtio-mmio",
    ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
