[package]
    name = "wateros-syscall-impl-kernel"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "../../syscall-api/api-v0/", package = "wateros-syscall-api-v0", default-features = true }
    task = { path = "../../../wateros-task/", package = "wateros-task", default-features = false }
    ipc = { path = "../../../wateros-ipc/", package = "wateros-ipc", default-features = false, optional = true }
    cred = { path = "../../../wateros-cred/", package = "wateros-cred", default-features = false, optional = true }
    mm = { path = "../../../wateros-mm/", package = "wateros-mm", default-features = true, optional = true }
    vfs = { path = "../../../wateros-vfs/", package = "wateros-vfs", default-features = false, optional = true }
    driver-input = { path = "../../../wateros-driver/driver-input/", package = "wateros-driver-input", default-features = false, optional = true }
    tty = { path = "../../../wateros-tty/", package = "wateros-tty", default-features = true, optional = true }
    network = { path = "../../../wateros-network/", package = "wateros-network", default-features = true, optional = true }
    log = { version = "0.4.29" }
    platform = { path = "../../../wateros-platform/", package = "wateros-platform", default-features = false }
    wateros-platform-arch-api-v0 = { path = "../../../wateros-platform/platform-arch/arch-api/api-v0/", default-features = true }
    spin = "0.10.0"
    wateros-base-config = { path = "../../../wateros-base/base-config/", package = "wateros-base-config", default-features = true }
    klog = { path = "../../../wateros-klog/", package = "wateros-klog", default-features = true }

[features]
    api-v0 = [ "api-v0/api-v0", "fd-session" ]
    bringup-stats = [  ]
    cred-session = [ "cred/api-v0", "cred/impl-root", "dep:cred" ]
    default = [ "impl-kernel" ]
    fd-session = [
        "cred-session",
        "dep:ipc",
        "dep:mm",
        "dep:tty",
        "dep:vfs",
        "dep:driver-input",
        "ipc/futex",
        "ipc/pipe",
        "ipc/shm",
        "ipc/signal",
        "mm/api-v0",
        "vfs/bridge-fs-api",
        "vfs/impl-fd-session",
        "driver-input/api-v0",
    ]
    impl-kernel = [
        "api-v0",
        "fd-session",
        "klog/default",
        "platform/api-v0",
        "socket-net",
    ]
    socket-net = [ "dep:network" ]
    user-copy-diagnostics = [  ]

[profile.dev]
    panic = "abort"

[profile.release]
    panic = "abort"
