[package]
    name = "wateros-runtime-logging"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    log = { version = "0.4.29" }
    console = { path = "../runtime-console/", package = "wateros-runtime-console", default-features = false }
[features]
    default = [  ]
    impl-debug = [  ]
    impl-dummy = [ "console/impl-dummy" ]
    impl-error = [  ]
    impl-firmware-console = [ "console/impl-firmware-console" ]
    impl-firmware-opensbi = [ "console/impl-firmware-opensbi" ]
    impl-info = [  ]
    impl-trace = [  ]
    impl-warn = [  ]
