[package]
    name = "wateros-runtime-logging"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    log = { version = "0.4.29" }
    console = { path = "../runtime-console/", package = "wateros-runtime-console", default-features = false }
[features]
    default = [ "impl-trace" ]
    impl-dummy = [ "console/impl-dummy" ]
    impl-firmware-console = [ "console/impl-firmware-console" ]
    impl-firmware-opensbi = [ "console/impl-firmware-opensbi" ]
    impl-trace = []
    impl-debug = []
    impl-info = []
    impl-warn = []
    impl-error = []
