[package]
    name = "wateros-platform-firmware"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "./firmware-api/api-v0/", package = "wateros-platform-firmware-api-v0", default-features = true }
    impl-dummy = { path = "./firmware-impl/impl-dummy/", package = "wateros-platform-firmware-impl-dummy", default-features = true }
    impl-opensbi = { path = "./firmware-impl/impl-opensbi/", package = "wateros-platform-firmware-impl-opensbi", default-features = true }

[features]
    api-v0 = [ "impl-dummy/api-v0", "impl-opensbi/api-v0" ]
    default = [ "api-v0", "impl-opensbi" ]
    impl-dummy = [  ]
    impl-opensbi = [  ]
