[package]
    name = "wateros-ipc-pipe-impl-ringbuf"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    api-v0 = { path = "../../pipe-api/api-v0/", package = "wateros-ipc-pipe-api-v0", default-features = true }
    base = { path = "../../../../wateros-base/", package = "wateros-base", default-features = true }
    waitqueue = { path = "../../../ipc-waitqueue/", package = "ipc-waitqueue", default-features = false }

[features]
    api-v0 = [  ]
    default = [ "api-v0" ]
    impl-loongarch64 = [ "waitqueue/impl-loongarch64" ]
    impl-riscv64 = [ "waitqueue/impl-riscv64" ]
